// Full list of 101 kanji + matching video files
const kanjiList = [
  { char: "出", file: "001_出.mp4" },
  { char: "回", file: "002_回.mp4" },
  { char: "十", file: "003_十.mp4" },
  { char: "弓", file: "004_弓.mp4" },
  { char: "穴", file: "005_穴.mp4" },
  { char: "木", file: "006_木.mp4" },
  { char: "鳥", file: "007_鳥.mp4" },
  { char: "王", file: "008_王.mp4" },
  { char: "来", file: "009_来.mp4" },
  { char: "食", file: "010_食.mp4" },
  { char: "百", file: "011_百.mp4" },
  { char: "車", file: "012_車.mp4" },
  { char: "日", file: "013_日.mp4" },
  { char: "麦", file: "014_麦.mp4" },
  { char: "貝", file: "015_貝.mp4" },
  { char: "口", file: "016_口.mp4" },
  { char: "書", file: "017_書.mp4" },
  { char: "行", file: "018_行.mp4" },
  { char: "千", file: "019_千.mp4" },
  { char: "皿", file: "020_皿.mp4" },
  { char: "月", file: "021_月.mp4" },
  { char: "豆", file: "022_豆.mp4" },
  { char: "角", file: "023_角.mp4" },
  { char: "耳", file: "024_耳.mp4" },
  { char: "言", file: "025_言.mp4" },
  { char: "止", file: "026_止.mp4" },
  { char: "万", file: "027_万.mp4" },
  { char: "一", file: "028_一.mp4" },
  { char: "火", file: "029_火.mp4" },
  { char: "山", file: "030_山.mp4" },
  { char: "羽", file: "031_羽.mp4" },
  { char: "手", file: "032_手.mp4" },
  { char: "大", file: "033_大.mp4" },
  { char: "交", file: "034_交.mp4" },
  { char: "寸", file: "035_寸.mp4" },
  { char: "二", file: "036_二.mp4" },
  { char: "音", file: "037_音.mp4" },
  { char: "川", file: "038_川.mp4" },
  { char: "虫", file: "039_虫.mp4" },
  { char: "足", file: "040_足.mp4" },
  { char: "小", file: "041_小.mp4" },
  { char: "向", file: "042_向.mp4" },
  { char: "尺", file: "043_尺.mp4" },
  { char: "三", file: "044_三.mp4" },
  { char: "糸", file: "045_糸.mp4" },
  { char: "雨", file: "046_雨.mp4" },
  { char: "馬", file: "047_馬.mp4" },
  { char: "力", file: "048_力.mp4" },
  { char: "白", file: "049_白.mp4" },
  { char: "歩", file: "050_歩.mp4" },
  { char: "上", file: "051_上.mp4" },
  { char: "四", file: "052_四.mp4" },
  { char: "刀", file: "053_刀.mp4" },
  { char: "風", file: "054_風.mp4" },
  { char: "魚", file: "055_魚.mp4" },
  { char: "目", file: "056_目.mp4" },
  { char: "青", file: "057_青.mp4" },
  { char: "考", file: "058_考.mp4" },
  { char: "中", file: "059_中.mp4" },
  { char: "五", file: "060_五.mp4" },
  { char: "舟", file: "061_舟.mp4" },
  { char: "水", file: "062_水.mp4" },
  { char: "羊", file: "063_羊.mp4" },
  { char: "首", file: "064_首.mp4" },
  { char: "人", file: "065_人.mp4" },
  { char: "多", file: "066_多.mp4" },
  { char: "入", file: "067_入.mp4" },
  { char: "下", file: "068_下.mp4" },
  { char: "六", file: "069_六.mp4" },
  { char: "門", file: "070_門.mp4" },
  { char: "土", file: "071_土.mp4" },
  { char: "肉", file: "072_肉.mp4" },
  { char: "毛", file: "073_毛.mp4" },
  { char: "子", file: "074_子.mp4" },
  { char: "少", file: "075_少.mp4" },
  { char: "示", file: "076_示.mp4" },
  { char: "本", file: "077_本.mp4" },
  { char: "七", file: "078_七.mp4" },
  { char: "戸", file: "079_戸.mp4" },
  { char: "石", file: "080_石.mp4" },
  { char: "皮", file: "082_皮.mp4" },
  { char: "心", file: "083_心.mp4" },
  { char: "女", file: "084_女.mp4" },
  { char: "高", file: "085_高.mp4" },
  { char: "走", file: "086_走.mp4" },
  { char: "玉", file: "087_玉.mp4" },
  { char: "八", file: "088_八.mp4" },
  { char: "衣", file: "089_衣.mp4" },
  { char: "金", file: "090_金.mp4" },
  { char: "米", file: "091_米.mp4" },
  { char: "犬", file: "092_犬.mp4" },
  { char: "母", file: "093_母.mp4" },
  { char: "長", file: "094_長.mp4" },
  { char: "生", file: "095_生.mp4" },
  { char: "立", file: "096_立.mp4" },
  { char: "九", file: "097_九.mp4" },
  { char: "矢", file: "098_矢.mp4" },
  { char: "田", file: "099_田.mp4" },
  { char: "竹", file: "100_竹.mp4" },
  { char: "牛", file: "101_牛.mp4" }
];

const grid = document.getElementById("kanji-grid");
const video = document.getElementById("video");

// Make buttons dynamically
kanjiList.forEach(item => {
  const btn = document.createElement("button");
  btn.textContent = item.char;
  btn.className = "kanji-btn";
  btn.onclick = () => {
    video.src = "videos/" + item.file;
    video.play();
  };
  grid.appendChild(btn);
});
